### ISSUE TITLE
yapıcağın koda tükirim

### ISSUE THREAD

**Issue by cenapyuce** [eaglethedev/rCaptcha-Solver#1]
iyi güzelde kanka niye düzgünce herşeyi koymuyon acc gen yapıcam 2 saat gereksinimleri aradım

**Comment by eaglethedev** [comment]
> iyi güzelde kanka niye düzgünce herşeyi koymuyon acc gen yapıcam 2 saat gereksinimleri aradım
> 
> 

dostum anladıgım kadarıyla pek kod okumayı bilmiyorsun discorda girmekten erimiş beynini birazcık kullansan zaten kodun üste importladıgım kütüphaneler var sadece "pip install kütüphaneismi" ile kurabilirsin yapacagın tek şey kodu kendi projene göre editlemek bunu bile yapamayacak statüde oldugunu düşünüyorum lütfen kod yazma, chatgptye falan yaptır daha saglıklı olur senin için.

**Comment by cenapyuce** [comment]
kankam öyle demiyorum piple indirdim bu skim sonik chrome driverı kullanmana kızıyorum yarım saatte anca buldum amk

**Comment by eaglethedev** [comment]
> kankam öyle demiyorum piple indirdim bu skim sonik chrome driverı kullanmana kızıyorum yarım saatte anca buldum amk

dedigin şeyin benle uzaktan yakından alakası yok chromedriver 115 artık sadece driver olarak yayınlanmıyor kullanım alanı genişledigi için yazılım geliştiricilere daha fazla imkan saglamak için açık kaynak oldu chromedriver version 115i indirmek istersen burdan bulabilirsin; https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/win32/chromedriver-win32.zip

+ bu kod 2captcha gibi servislere para verilmemesi için geliştirilmiş bir kod zaten parası olan bunu kullanmakla ugraşmaz 

`from capmonster_python import RecaptchaV2Task
capmonster = RecaptchaV2Task(apikey)
task_id = capmonster.create_task("http://mail.com.tr/signup",sitekey)
result = capmonster.join_task_result(task_id)
result = result.get("gRecaptchaResponse")
browser.execute_script(f"document.getElementsByClassName('g-recaptcha-response')[0].innerHTML = '{result}'; ")`

bu kodu kullanır

**Comment by cenapyuce** [comment]
tamam kanka az önce atarlandın ya ondan dedim
neyse teşşekür ederim.

**Comment by eaglethedev** [comment]
> tamam kanka az önce atarlandın ya ondan dedim neyse teşşekür ederim.

<3
